language: cpp

env:
  - LLVM_VERSION=3.8 GCC_VERSION=4.8
  - LLVM_VERSION=3.8 GCC_VERSION=4.9
  - LLVM_VERSION=3.8 GCC_VERSION=6
  - LLVM_VERSION=3.8 GCC_VERSION=7

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8
      - g++-4.8
      - gcc-4.9
      - g++-4.9
      - gcc-6
      - g++-6
      - gcc-7
      - g++-7
      - llvm-3.8
      - llvm-3.8-dev
      - clang-3.8
      - libhdf5-serial-dev
      - libsqlite3-dev

before_install:
 - if [[ $CXX = "g++" ]]; then
     export CXX="g++-${GCC_VERSION}";
     export CC="gcc-${GCC_VERSION}";
   else
     export CXX="clang++-${LLVM_VERSION}";
     export CC="clang-${LLVM_VERSION}";
   fi
 - if `type h5c++ > /dev/null 2>&1`; then
     export HDF5_CXX="$CXX";
   else
     export H5CXX="$CXX";
     export H5LIBS="-lhdf5 -lhdf5_cpp";
   fi
 - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"
 - export EXTRA_CXXFLAGS="-std=c++11"
 - export BF_CLANG="clang-${LLVM_VERSION}"
 - export BF_CLANGXX="clang++-${LLVM_VERSION}"
 - export BF_GCC="gcc-${GCC_VERSION}"
 - export BF_GXX="g++${GCC_VERSION}"
 - export LLVM_CXXFLAGS="`$LLVM_CONFIG --cxxflags | sed -e 's/-Werror=date-time//g' -e 's/-gsplit-dwarf//g'` -fno-rtti"
 - export LLVM_CFLAGS=`$LLVM_CONFIG --cflags | sed -e 's/-Werror=date-time//g' -e 's/-gsplit-dwarf//g'`

script:
  - autoreconf -i &&
    PATH="/usr/lib/ccache:$PATH" ./configure CXXFLAGS="$LLVM_CXXFLAGS -std=c++11" CFLAGS="$LLVM_CFLAGS" &&
    make distcheck DISTCHECK_CONFIGURE_FLAGS="CXXFLAGS='$LLVM_CXXFLAGS -std=c++11' LLVM_CFLAGS='$LLVM_CFLAGS'"

compiler:
  - clang
  - gcc
