language: cpp

env:

  - LLVM_VERSION=5.0 GCC_VERSION=6
  - LLVM_VERSION=5.0 GCC_VERSION=7
  - LLVM_VERSION=5.0 GCC_VERSION=8
  - LLVM_VERSION=6.0 GCC_VERSION=6
  - LLVM_VERSION=6.0 GCC_VERSION=7
  - LLVM_VERSION=6.0 GCC_VERSION=8
  - LLVM_VERSION=7   GCC_VERSION=6
  - LLVM_VERSION=7   GCC_VERSION=7
  - LLVM_VERSION=7   GCC_VERSION=8

sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-6
      - g++-6
      - gcc-7
      - g++-7
      - gcc-8
      - g++-8
      - llvm-6.0
      - llvm-6.0-dev
      - clang-6.0
      - llvm-7
      - llvm-7-dev
      - clang-7
      - libhdf5-serial-dev
      - libsqlite3-dev

before_install:
 - if [[ $CXX = "g++" ]]; then
     export CXX="g++-${GCC_VERSION}";
     export CC="gcc-${GCC_VERSION}";
   else
     export CXX="clang++-${LLVM_VERSION}";
     export CC="clang-${LLVM_VERSION}";
   fi
 - if `type h5c++ > /dev/null 2>&1`; then
     export HDF5_CXX="$CXX";
   else
     export H5CXX="$CXX";
     export H5LIBS="-lhdf5 -lhdf5_cpp";
   fi
 - export LLVM_CONFIG="llvm-config-${LLVM_VERSION}"
 - export EXTRA_CXXFLAGS="-std=c++11 -fno-rtti"
 - export BF_CLANG="clang-${LLVM_VERSION}"
 - export BF_CLANGXX="clang++-${LLVM_VERSION}"
 - export BF_GCC="gcc-${GCC_VERSION}"
 - export BF_GXX="g++${GCC_VERSION}"
 - export LLVM_CXXFLAGS="`$LLVM_CONFIG --cxxflags | sed -e 's/-Werror=date-time//g' -e 's/-Wl,--no-keep-files-mapped//g' -e 's/-Wl,--no-map-whole-files//g' -e 's/-gsplit-dwarf//g'`"
 - export LLVM_CFLAGS=`$LLVM_CONFIG --cflags | sed -e 's/-Werror=date-time//g' -e 's/-Wl,--no-keep-files-mapped//g' -e 's/-Wl,--no-map-whole-files//g' -e 's/-gsplit-dwarf//g'`

script:
  - autoreconf -i &&
    PATH="/usr/lib/ccache:$PATH" ./configure CXXFLAGS="$LLVM_CXXFLAGS $EXTRA_CXXFLAGS" CFLAGS="$LLVM_CFLAGS" &&
    make distcheck DISTCHECK_CONFIGURE_FLAGS="CXXFLAGS='$LLVM_CXXFLAGS $EXTRA_CXXFLAGS' LLVM_CFLAGS='$LLVM_CFLAGS'"
  - find . -name test-suite.log | xargs cat

compiler:
  - clang
  - gcc
