sudo: false
language: cpp
dist: xenial

env:
  - LLVM_VERSION=6.0 GCC_VERSION=8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
    packages:
      - clang-6.0
      - llvm-6.0-dev
      - gcc-8
      - g++-8
      - ccache
#      - libhdf5-dev
      - libsqlite3-dev

before_install:
  - if [[ $CXX = "g++" ]]; then
      export CXX="/usr/bin/g++-${GCC_VERSION}";
      export CC="/usr/bin/gcc-${GCC_VERSION}";
    else
      export CXX="/usr/bin/clang++-${LLVM_VERSION}";
      export CC="/usr/bin/clang-${LLVM_VERSION}";
    fi
  - export BF_CLANG="/usr/bin/clang-${LLVM_VERSION}"
  - export BF_CLANGXX="/usr/bin/clang++-${LLVM_VERSION}"
  - export HDF5_CXX="$CXX"
  - export HDF5_CXXLINKER="$CXX"

script:
  - mkdir build
  - cd build
  - >
      cmake -DCMAKE_INSTALL_PREFIX="$HOME/bytesflops"
      -DCMAKE_PREFIX_PATH=/usr
      -DCMAKE_MODULE_PATH="/usr/lib/llvm-${LLVM_VERSION}/cmake"
      -DCMAKE_C_COMPILER="$CC"
      -DCMAKE_CXX_COMPILER="$CXX"
      -DCLANG_EXECUTABLE="$BF_CLANG"
      -DCLANGXX_EXECUTABLE="$BF_CLANGXX"
      -DOPT_EXECUTABLE="/usr/bin/opt-${LLVM_VERSION}"
      -DCMAKE_C_FLAGS="-I/usr/include/llvm-${LLVM_VERSION} -g"
      -DCMAKE_CXX_FLAGS="-I/usr/include/llvm-${LLVM_VERSION} -g -fno-rtti"
      ..
  - make VERBOSE=1 -k
  - make CTEST_OUTPUT_ON_FAILURE=1 test
  - make install

compiler:
  - clang
  - gcc
